
package com.example.jaxws.soap.client.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InboundPocProv", targetNamespace = "/pocprov_V1.0", wsdlLocation = "http://172.27.9.7:8686/services/InboundPocProv?wsdl")
public class InboundPocProv
    extends Service
{

    private final static URL INBOUNDPOCPROV_WSDL_LOCATION;
    private final static WebServiceException INBOUNDPOCPROV_EXCEPTION;
    private final static QName INBOUNDPOCPROV_QNAME = new QName("/pocprov_V1.0", "InboundPocProv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.27.9.7:8686/services/InboundPocProv?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INBOUNDPOCPROV_WSDL_LOCATION = url;
        INBOUNDPOCPROV_EXCEPTION = e;
    }

    public InboundPocProv() {
        super(__getWsdlLocation(), INBOUNDPOCPROV_QNAME);
    }

    public InboundPocProv(WebServiceFeature... features) {
        super(__getWsdlLocation(), INBOUNDPOCPROV_QNAME, features);
    }

    public InboundPocProv(URL wsdlLocation) {
        super(wsdlLocation, INBOUNDPOCPROV_QNAME);
    }

    public InboundPocProv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INBOUNDPOCPROV_QNAME, features);
    }

    public InboundPocProv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InboundPocProv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KnSubsProvInbound
     */
    @WebEndpoint(name = "Port")
    public KnSubsProvInbound getPort() {
        return super.getPort(new QName("/pocprov_V1.0", "Port"), KnSubsProvInbound.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KnSubsProvInbound
     */
    @WebEndpoint(name = "Port")
    public KnSubsProvInbound getPort(WebServiceFeature... features) {
        return super.getPort(new QName("/pocprov_V1.0", "Port"), KnSubsProvInbound.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INBOUNDPOCPROV_EXCEPTION!= null) {
            throw INBOUNDPOCPROV_EXCEPTION;
        }
        return INBOUNDPOCPROV_WSDL_LOCATION;
    }

}
